M48
; DRILL file {KiCad (6.0.1-0)} date 2022 February 26, Saturday 01:42:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-26T01:42:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X112.1Y-96.3
X144.9Y-63.5
X144.9Y-129.0
X177.7Y-96.2
T0
M30
